package com.aperam.sig.bobina;

public enum EstadoProductivo {

    PENDIENTE_CONTROL,
    STOCK,
    RETRABAJO,
    SCRAP,
    PENDIENTE_PRODUCCION,
    PROD_FLEJADORA_GRANDE,
    PROD_FLEJADORA_CHICA,
    PROD_MECESA,
    PENDIENTE_CORROBORACION,
    CORROBORADA,
    RECHAZADA,
    CORROBORADA_STOCK,
    CORROBORADA_DESPACHO,
    CORROBORADA_DESPACHO_PRONOSTICADO

}
