package com.aperam.sig.producto;

public enum EstadoProductivo {

    PENDIENTE_CORROBORACION,
    CORROBORADA,
    RECHAZADA,
    CORROBORADA_STOCK,
    CORROBORADA_DESPACHO,
    CORROBORADA_DESPACHO_PRONOSTICADO

}
